name: sensors_checker_example
description: "Demonstrates how to use the sensors_checker plugin."
version: 0.0.1+1
publish_to: "none"

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  sensors_checker:
    path: ../
