name: sensors_checker
description: "Plugin for detecting sensors availability."
version: 1.0.0+1
homepage: https://github.com/paamand/sensors_checker
repository: https://github.com/paamand/sensors_checker

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: eu.paamand.sensors_checker
        pluginClass: SensorsCheckerPlugin
      ios:
        pluginClass: SensorsCheckerPlugin

